In [60]:
import numpy as np

In [61]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],[np.sin(np.pi/6), np.cos(np.pi/6)]])

In [62]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [63]:
x = np.array([[1],[0]])
x

array([[1],
       [0]])

In [64]:
x, x.transpose()

(array([[1],
        [0]]), array([[1, 0]]))

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [65]:
R*x

array([[ 0.8660254, -0.5      ],
       [ 0.       ,  0.       ]])

In [66]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [73]:
x1 = R.dot(R.dot(x))
x1

array([[0.5      ],
       [0.8660254]])

# 2. Создайте вектор-столбец v, с координатами 0 по иксу, 2 по игреку. Вычислите вектор-столбец w как результат поворота v на 30 градусов при помощи матрицы R

In [74]:
v = np.array([[0],[2]])
v

array([[0],
       [2]])

In [76]:
x2 = R.dot(v)
x2

array([[-1.        ],
       [ 1.73205081]])

# 3. Найдите квадрат матрицы R.

In [78]:
R.dot(R)

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

# 4. Напишите функцию Prod(x,y), которая вовращает скалярное произведение векоторов-столбцов x и y. Проверьте, найдя скалярное произведение вектора (2,0) на себя, и скалярное произведение перпендикулярных векторов (3,5) и (-5,3)

In [83]:
def Prod(x, y):
    return x.dot(y)

In [90]:
v1 = np.array([2, 0])
v2 = np.array([3, 5])
v3 = np.array([-5, 3])

In [94]:
Prod(v1, v1)

4

In [93]:
Prod(v2, v3)

0

# 5. Метод Гаусса
Пусть имеется матрица 3x4 
    
    A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])

Получите с помощью операций над слайсами результат зану

In [171]:
A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])
A

array([[ 1,  2,  0, -1],
       [ 2,  3,  1,  4],
       [ 3,  3,  3,  3]])

In [172]:
sizeX, sizeY = A.shape
for i in range(sizeY-1):
    if(A[i][i]!=1):
        A[i][i:] = A[i][i:] / A[i][i]
    for j in range(i+1, sizeY):
        A[j][i:] = A[j][i:] - A[i][i:] * A[j][i]
    for j in range(0, i):
        A[j][i:] = A[j][i:] - A[i][i:] * A[j][i]
A

IndexError: index 3 is out of bounds for axis 0 with size 3