In [105]:
import numpy as np

In [106]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [107]:
x = np.array([[1],[0]])
x

array([[1],
       [0]])

In [108]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],[np.sin(np.pi/6), np.cos(np.pi/6)]])

In [109]:
x, x.transpose()

(array([[1],
        [0]]), array([[1, 0]]))

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [110]:
R*x

array([[ 0.8660254, -0.5      ],
       [ 0.       ,  0.       ]])

In [111]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [112]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [113]:
R.dot(R.dot(x))

array([[0.5      ],
       [0.8660254]])

In [114]:
R.dot([0,2])

array([-1.        ,  1.73205081])

In [115]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

In [116]:
R.dot(R)

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

In [117]:
A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])

In [130]:
W = A.dot(0)

In [131]:
W

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
def Prod(x,y):
    return x.transpose().dot(y)[0,0]