In [1]:
import numpy as np

In [2]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],[np.sin(np.pi/6), np.cos(np.pi/6)]])

In [3]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [4]:
x = np.array([[1],[0]])
x

array([[1],
       [0]])

In [5]:
x, x.transpose()

(array([[1],
        [0]]), array([[1, 0]]))

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [6]:
R*x

array([[ 0.8660254, -0.5      ],
       [ 0.       ,  0.       ]])

In [7]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [8]:
R.dot(R.dot(x))

array([[0.5      ],
       [0.8660254]])

# 2. Создайте вектор-столбец у, с координатами 0 по иксу, 2 по игреку. Вычислите z как результат поворота y на 30 градусов при помощи матрицы R

In [15]:
y = np.array([[0],[2]])
z = R.dot(y)
z

array([[-1.        ],
       [ 1.73205081]])

# 3. Найдите квадрат матрицы R

In [14]:
R_sqr = R.dot(R)
R_sqr

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

# 4.

In [35]:
def Prod(x,y):
    return (x.flatten() * y.flatten()).sum()
    

In [37]:
Prod(np.array([[0],[2]]),np.array([[0],[2]]))

4

In [38]:
Prod(np.array([[3],[5]]),np.array([[-5],[3]]))

0

In [73]:
A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]], dtype='float64')

In [70]:
#5
for i in range(A.shape[0] - 1):
    for j in range(i + 1, A.shape[0]):
        if(A[i, i] == 0):
            continue
        d = A[j, i] / A[i, i]
        A[j] = A[j] - A[i] * d
for z in range(A.shape[0] - 1):
    i = A.shape[0] - z - 1
    for w in range(z + 1, A.shape[0]):
        j = A.shape[0] - w - 1
        if(A[i, i] == 0):
            continue
        d = A[j, i] / A[i, i]
        A[j] = A[j] - A[i] * d
print(A)

[[  1.   0.   2.  11.]
 [  0.  -1.   1.   6.]
 [  0.   0.   0. -12.]]


In [101]:
#6
A1 = np.array([[1,0,0],[-2,1,0], [-3,0,1] ], dtype='float64')

In [106]:
A2 = np.array([[1,2,0], [0,1,0], [0,-3,1]], dtype='float64')

In [72]:
print(A)

[[ 1.  2.  0. -1.]
 [ 2.  3.  1.  4.]
 [ 3.  3.  3.  3.]]


In [107]:
A2.dot(A1.dot(A))

array([[  1.,   0.,   2.,  11.],
       [  0.,  -1.,   1.,   6.],
       [  0.,   0.,   0., -12.]])