In [8]:
import numpy as np

In [38]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],[np.sin(np.pi/6), np.cos(np.pi/6)]])

In [39]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [22]:
x = np.array([[0],[2]])
x

array([[0],
       [2]])

In [12]:
x, x.transpose()

(array([[1],
        [0]]), array([[1, 0]]))

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [13]:
R*x

array([[ 0.8660254, -0.5      ],
       [ 0.       ,  0.       ]])

In [18]:
R.dot(x)

array([[0.17320508],
       [0.1       ]])

TypeError: list indices must be integers or slices, not tuple

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [16]:
R.dot( R.dot(x))

array([[0.5      ],
       [0.8660254]])

In [41]:
R.dot(x)

array([[-1.        ],
       [ 1.73205081]])

In [40]:
R.dot(R)

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

In [49]:
x.transpose()

array([[0, 2]])

In [54]:
def Prod(x,y):
    return x.transpose().dot(y)[0,0]



In [55]:
Prod (x,x)


4

In [61]:
x.transpose()

array([[0, 2]])

In [62]:
Prod (3,-5)

AttributeError: 'int' object has no attribute 'transpose'