In [1]:
import numpy as np

In [2]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],[np.sin(np.pi/6), np.cos(np.pi/6)]])

In [3]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [26]:
x = np.array([[0],[2]])
x

array([[0],
       [2]])

In [5]:
x, x.transpose()

(array([[1],
        [0]]), array([[1, 0]]))

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [6]:
R*x

array([[ 0.8660254, -0.5      ],
       [ 0.       ,  0.       ]])

In [7]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [21]:
R.dot(R.dot(x))

array([[0.5      ],
       [0.8660254]])

2.



In [27]:
R.dot(x)

array([[-1.        ],
       [ 1.73205081]])

3.

In [30]:
R.dot(R)

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

4.

In [56]:
def Prod(x,y):
    return x.transpose().dot(y)[0,0]

In [55]:
v=np.array([[0],[2]])
Prod(v,v)

4

In [45]:
v.shape

(2, 1)

In [46]:
z = np.array([1,2,3,4])
z.shape

(4,)

5.

In [49]:
A=np.array([[1,2,0,-1],[2,3,1,4],[3,3,3,3]])
A

array([[ 1,  2,  0, -1],
       [ 2,  3,  1,  4],
       [ 3,  3,  3,  3]])

In [50]:
A[0]

array([ 1,  2,  0, -1])

In [51]:
A=np.array([[1,2,0,-1],[2,3,1,4],[3,3,3,3]])
A.flatten()

array([ 1,  2,  0, -1,  2,  3,  1,  4,  3,  3,  3,  3])