In [23]:
import numpy as np

In [24]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],[np.sin(np.pi/6), np.cos(np.pi/6)]])

In [25]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [26]:
x = np.array([[1],[0]])
x

array([[1],
       [0]])

In [27]:
x, x.transpose()

(array([[1],
        [0]]), array([[1, 0]]))

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [28]:
R*x

array([[ 0.8660254, -0.5      ],
       [ 0.       ,  0.       ]])

In [29]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [30]:
R.dot(R.dot(x))

array([[0.5      ],
       [0.8660254]])

In [33]:
v = np.array([0,2])

In [34]:
w = R.dot(v)

In [35]:
w

array([-1.        ,  1.73205081])

In [36]:
# 3.

In [40]:
np.linalg.matrix_power(R, 2) 

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

In [43]:
R.dot(R)

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

# 4. Напишите функцию Prod(x,y), которая вовращает скалярное произведение векоторов-столбцов x и y. Проверьте, найдя скалярное произведение вектора (0,2) на себя, и скалярное произведение перпендикулярных векторов (3,5) и (-5,3)


In [49]:
def Prod(x,y):
    return sum(np.array(x)*np.array(y))
            

In [50]:
Prod([0,2],[0,2])

4

In [51]:
Prod([3,5],[-5,3])

0

# 5. Метод Гаусса
Пусть имеется матрица 3x4

A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])
Получите с помощью операций над слайсами результат зануления элементов в первом столбце на первом шаге метода Гаусса

In [136]:
A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]])

In [137]:
A

array([[ 1,  2,  0, -1],
       [ 2,  3,  1,  4],
       [ 3,  3,  3,  3]])

In [138]:
for k in range(len(A-1)):
    for i in range(len(A)):
        A[i]=A[i]/A[i][k]
    for i in range(k+1,len(A)):
        A[i]=A[i]-A[k]

c:\program files (x86)\python37-32\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until
c:\program files (x86)\python37-32\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [139]:
A

array([[-2147483648, -2147483648, -2147483648, -2147483648],
       [-2147483648, -2147483648, -2147483648, -2147483648],
       [          0,           0,           1,          -1]])