In [1]:
import numpy as np

In [2]:
R = np.array([[np.cos(np.pi/6), -np.sin(np.pi/6)],[np.sin(np.pi/6), np.cos(np.pi/6)]])

In [3]:
R

array([[ 0.8660254, -0.5      ],
       [ 0.5      ,  0.8660254]])

In [4]:
x = np.array([[1],[0]])
x

array([[1],
       [0]])

In [5]:
x, x.transpose()

(array([[1],
        [0]]), array([[1, 0]]))

Умножение звездочкой - поэлементное, а не умножение матриц (столбцов, строк). Проверим:

In [6]:
R*x

array([[ 0.8660254, -0.5      ],
       [ 0.       ,  0.       ]])

In [7]:
R.dot(x)

array([[0.8660254],
       [0.5      ]])

# 1. Совершите два поворота x на 30 градусов каждый при помощи матрицы R

In [8]:
R.dot(R.dot(x))

array([[0.5      ],
       [0.8660254]])

# 2. Создайте вектор-столбец у, с координатами 0 по иксу, 2 по игреку. Вычислите z как результат поворота y на 30 градусов при помощи матрицы R

In [9]:
y = np.array([[0],[2]])
z = R.dot(y)
z

array([[-1.        ],
       [ 1.73205081]])

# 3. Найдите квадрат матрицы R

In [10]:
R_sqr = R.dot(R)
R_sqr

array([[ 0.5      , -0.8660254],
       [ 0.8660254,  0.5      ]])

# 4.

In [44]:
def Prod(x,y):
    return (x.flatten() * y.flatten()).sum()
    

Prod(np.array([[0],[2]]),np.array([[0],[2]]))

4

In [ ]:
Prod(np.array([[3],[5]]),np.array([[-5],[3]]))

In [45]:
#5
A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]], dtype='float64')

for i in range(A.shape[0] - 1):
    for j in range(i + 1, A.shape[0]):
        if(A[i, i] == 0):
            continue
        d = A[j, i] / A[i, i]
        A[j] = A[j] - A[i] * d
for z in range(A.shape[0] - 1):
    i = A.shape[0] - z - 1
    for w in range(z + 1, A.shape[0]):
        j = A.shape[0] - w - 1
        if(A[i, i] == 0):
            continue
        d = A[j, i] / A[i, i]
        A[j] = A[j] - A[i] * d
print(A)

[[  1.   0.   2.  11.]
 [  0.  -1.   1.   6.]
 [  0.   0.   0. -12.]]


In [38]:
#6
A1 = np.array([[1,0,0],[-2,1,0], [-3,0,1] ], dtype='float64')
A2 = np.array([[1,2,0], [0,1,0], [0,-3,1]], dtype='float64')

A = np.array([[1,2,0,-1], [2,3,1,4], [3,3,3,3]], dtype='float64')

A2.dot(A1.dot(A))

array([[  1.,   0.,   2.,  11.],
       [  0.,  -1.,   1.,   6.],
       [  0.,   0.,   0., -12.]])

In [43]:
#7
def LU_decomp(A):
    L = np.zeros(shape=A.shape)
    U = np.zeros(shape=A.shape)
    for i in range(A.shape[0]):
        U[0,i] = A[0,i]
        if U[0,0] != 0:
            L[i,0] = A[i,0]/U[0,0]
    for i in range(1, A.shape[0]):
        for j in range(i, A.shape[0]):
            U[i,j] = A[i,j] - (L[i,:i].flatten() * U[:i,j].flatten()).sum()
        for j in range(i, A.shape[0]):
            if(U[i,i] !=0 ):
                L[j,i] = (1/U[i,i]) * (A[j,i] - (L[j,:i].flatten() * U[:i,i].flatten()).sum())
    return L, U

B = np.array([[1,2,0], [2,3,1], [3,3,3]], dtype='float64')

B1 = np.array([[1,2,0], [0,3,1], [0,0,3]], dtype='float64')

B2 = np.array([[1,0,0], [2,3,0], [3,3,0]], dtype='float64')

np.zeros(shape=(3,3))[:,2].sum()          
    

B1, B2 = LU_decomp(B)
print("B1 x B2:\n", B1.dot(B2), "\n")
print("B:\n",B)

B1 x B2:
 [[1. 2. 0.]
 [2. 3. 1.]
 [3. 3. 3.]] 

B:
 [[1. 2. 0.]
 [2. 3. 1.]
 [3. 3. 3.]]
